# Your Name or Company
title: Varun Singh

# Description of your website. This is used for social sharing.
description:  Varun Singh

# A brief blurb about yourself
content: Varun Singh

# Add your social links
social:
  - platform: github
    url: 
  - platform: facebook
    url: 
  - platform: twitter
    url: 
  - platform: linkedin
    url: 

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: vsingh.png
google_analytics: "" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
